services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Elements\Bundle\AlternateObjectTrees\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    Elements\Bundle\AlternateObjectTreesBundle\Installer:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('ElementsAlternateObjectTreesBundle')"
